/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* THIS IS A MODIFIED MAIN FILE FOR THE fish PROJECT.
* It uses the on-board camera on the MAX78000 FTHR to capture an image and
* classify it with your quantized fish model (3 classes), and can show a
* simple ASCII preview of the image over UART.
*******************************************************************************/

// fish
// Generated by ai8xize.py for MAX78000 and then adapted from your emotion_gen
// camera demo.

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

#include "mxc.h"
#include "cnn.h"

#include "mxc_device.h"
#include "mxc_sys.h"
#include "fcr_regs.h"
#include "icc.h"
#include "led.h"
#include "tmr.h"
#include "dma.h"
#include "pb.h"
#include "mxc_delay.h"
#include "camera.h"
#include "board.h"

volatile uint32_t cnn_time;   // Set in cnn.c interrupt handler

// ────────────────────────────────────────────────────────────
// Camera / image settings (same as emotion demo)
// ────────────────────────────────────────────────────────────
#define IMAGE_SIZE_X   (64 * 2)      // 128
#define IMAGE_SIZE_Y   (64 * 2)      // 128
#define CAMERA_FREQ    (5 * 1000 * 1000) // 5 MHz

// Confidence threshold: 0.8 -> 80.0% -> 800 in "percent x10" units
#define CONF_THRESH_X10 800

// Enable ASCII preview
#define ASCII_ART

// ASCII downsample ratio (2 → roughly 64×64 chars)
#define ASCII_RATIO    2

// Simple brightness map
static const char ascii_chars[] = " .:-=+*#%@";

// RGB565 buffer for TFT (kept from emotion demo, harmless even if unused)
static uint8_t data565[IMAGE_SIZE_X * 2];

// CNN I/O
static uint32_t input_0[IMAGE_SIZE_X * IMAGE_SIZE_Y];   // HWC, 0x00bbggrr ^ 0x00808080
static int32_t  ml_data[CNN_NUM_OUTPUTS];
static q15_t    ml_softmax[CNN_NUM_OUTPUTS];

// 3 fish classes
static const char classes[CNN_NUM_OUTPUTS][20] = {
    "bangus",
    "gold_fish",
    "gourami"
};

void fail(void)
{
    printf("\n*** FAIL ***\n\n");
    while (1) { }
}

// ────────────────────────────────────────────────────────────
// Load input_0 into CNN FIFO (same pattern as ai8x generated code)
// ────────────────────────────────────────────────────────────
void load_input(void)
{
    const uint32_t *in0 = input_0;

    for (int i = 0; i < 16384; i++) {   // 128*128 = 16384 pixels
        // Wait for FIFO 0 ready (avoid overrun)
        while ((*((volatile uint32_t *)0x50000004) & 1) != 0) {
        }
        *((volatile uint32_t *)0x50000008) = *in0++; // Write FIFO 0
    }
}

// ────────────────────────────────────────────────────────────
// Capture one frame from camera + convert to CNN input_0[]
// This is essentially your emotion_gen capture_process_camera(),
// just reused for fish.
// ────────────────────────────────────────────────────────────
void capture_process_camera(void)
{
    uint8_t  *raw;
    uint32_t imgLen;
    uint32_t w, h;
    int      cnt = 0;
    uint8_t  r, g, b;
    uint16_t rgb;
    int      j = 0;
    uint8_t *data = NULL;
    stream_stat_t *stat;

    // Start capture
    camera_start_capture_image();

    // Get general image info (optional)
    camera_get_image(&raw, &imgLen, &w, &h);
    printf("W:%lu H:%lu L:%lu\n", (unsigned long)w, (unsigned long)h, (unsigned long)imgLen);

    // Get image line by line from streaming FIFO
    for (int row = 0; row < (int)h; row++) {
        // Wait until camera streaming buffer is full
        while ((data = get_camera_stream_buffer()) == NULL) {
            if (camera_is_image_rcv()) {
                break;
            }
        }

        j = 0;
        for (int k = 0; k < 4 * (int)w; k += 4) {
            // data format: 0x00bbggrr
            r = data[k];
            g = data[k + 1];
            b = data[k + 2];
            // data[k + 3] is padding, skip

            // Encode for CNN: [0,255] -> signed Q7-style in 0x00bbggrr ^ 0x00808080
            input_0[cnt++] = ((b << 16) | (g << 8) | r) ^ 0x00808080;

            // Optional RGB565 (for TFT, not required)
            rgb = ((r & 0b11111000) << 8) |
                  ((g & 0b11111100) << 3) |
                  (b >> 3);
            data565[j]     = (rgb >> 8) & 0xFF;
            data565[j + 1] = rgb & 0xFF;
            j += 2;
        }

        // Release stream buffer
        release_camera_stream_buffer();
    }

    // Check for overflow
    stat = get_camera_stream_statistic();
    if (stat->overflow_count > 0) {
        printf("OVERFLOW DISP = %d\n", stat->overflow_count);
        LED_On(LED2); // Turn on red LED if overflow detected
        while (1) { }
    }
}

// ────────────────────────────────────────────────────────────
// ASCII preview from input_0 (same idea as your old demo)
// ────────────────────────────────────────────────────────────
#ifdef ASCII_ART
void asciiart(uint8_t *img)
{
    int skip_x, skip_y;
    uint8_t r, g, b, Y;
    uint8_t *srcPtr = img;
    int l = (int)strlen(ascii_chars) - 1;

    skip_x = ASCII_RATIO;
    skip_y = ASCII_RATIO;

    for (int i = 0; i < IMAGE_SIZE_Y; i++) {
        for (int j = 0; j < IMAGE_SIZE_X; j++) {
            // input_0 format: 0x00bbggrr ^ 0x00808080
            // undo 0x80: (Q7 -> 0..255)
            r = *srcPtr++ ^ 0x80;
            g = *srcPtr++ ^ 0x80;
            b = *srcPtr++ ^ 0x80;
            srcPtr++; // skip msb = 0x00

            // simple luminance
            Y = (uint8_t)((3 * r + b + 4 * g) >> 3);

            if ((skip_x == ASCII_RATIO) && (skip_y == ASCII_RATIO)) {
                int idx = (Y * l) / 255;
                if (idx < 0) idx = 0;
                if (idx > l) idx = l;
                putchar(ascii_chars[l - idx]);  // brighter → denser char
            }

            skip_x++;
            if (skip_x > ASCII_RATIO) {
                skip_x = 1;
            }
        }

        skip_y++;
        if (skip_y > ASCII_RATIO) {
            printf("\n");
            skip_y = 1;
        }
    }
}
#endif // ASCII_ART

// ────────────────────────────────────────────────────────────
// Softmax helper
// ────────────────────────────────────────────────────────────
void softmax_layer(void)
{
    cnn_unload((uint32_t *)ml_data);
    softmax_q17p14_q15((const q31_t *)ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

// ────────────────────────────────────────────────────────────
// main
// ────────────────────────────────────────────────────────────
int main(void)
{
    int i;
    int digs, tens;
    int ret = 0;
    int result[CNN_NUM_OUTPUTS] = {0};
    int dma_channel;

    // For confidence threshold decision
    int best_idx   = -1;
    int best_p10   = -1;  // probability * 10 (e.g. 805 -> 80.5%)
    int p10        = 0;

    int thr_int = CONF_THRESH_X10 / 10;
    int thr_dec = CONF_THRESH_X10 % 10;

#if defined(BOARD_FTHR_REVA)
    // Wait for PMIC 1.8V to become available (~180ms after power-up)
    MXC_Delay(200000);

    // Enable camera power
    Camera_Power(POWER_ON);

    printf("\n\nFish Classification Feather Demo\n");
#endif

    MXC_ICC_Enable(MXC_ICC0); // Enable cache

    // Switch to 100 MHz clock
    MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
    SystemCoreClockUpdate();

    printf("Waiting...\n");

    // Let debugger interrupt if needed
    MXC_Delay(SEC(2));

    // Enable CNN clock (APB 50 MHz div 1)
    cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK,
               MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

    printf("\n*** CNN Inference Test fish (camera) ***\n");

    cnn_init();         // Bring state machine into consistent state
    cnn_load_weights(); // Load kernels
    cnn_load_bias();    // Load bias
    cnn_configure();    // Configure state machine

    // ───── Camera init (copied from emotion demo) ─────
    MXC_DMA_Init();
    dma_channel = MXC_DMA_AcquireChannel();

    printf("Init Camera.\n");
    ret = camera_init(CAMERA_FREQ);
    if (ret != STATUS_OK) {
        printf("Error from camera_init: %d\n", ret);
        return -1;
    }

    ret = camera_setup(IMAGE_SIZE_X, IMAGE_SIZE_Y,
                       PIXFORMAT_RGB888,
                       FIFO_THREE_BYTE,
                       STREAMING_DMA,
                       dma_channel);
    if (ret != STATUS_OK) {
        printf("Error from camera_setup: %d\n", ret);
        return -1;
    }

    // Same tweak as emotion demo to avoid overflow
    camera_write_reg(0x11, 0x00);

    printf("********** Press PB1 (SW1) to capture an image **********\r\n");
    while (!PB_Get(0)) {
        // wait for button press
    }

    // Main loop: capture → run CNN → print result + ASCII
    while (1) {
        LED_Off(LED1);
        LED_Off(LED2);

        // Capture one frame into input_0[]
        capture_process_camera();

        cnn_time = 0;
        cnn_start();   // Start CNN
        load_input();  // Load data into FIFO

        // Wait for CNN interrupt (cnn_time set in ISR)
        SCB->SCR &= ~SCB_SCR_SLEEPDEEP_Msk; // SLEEPDEEP = 0
        while (cnn_time == 0) {
            __WFI();
        }

        softmax_layer();

        printf("\n*** DONE ***\n\n");
#ifdef CNN_INFERENCE_TIMER
        printf("Approximate data loading and inference time: %u us\n\n", cnn_time);
#endif

        printf("Classification results:\n");

        best_idx = -1;
        best_p10 = -1;

        for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
            // probability * 1000
            p10 = (1000 * ml_softmax[i] + 0x4000) >> 15;  // ~ prob*1000

            tens = p10 % 10;   // decimal digit
            digs = p10 / 10;   // integer percent

            result[i] = digs;

            if (p10 > best_p10) {
                best_p10 = p10;
                best_idx = i;
            }

            printf("[%7d] -> %-10s: %d.%d%%\r\n",
                   ml_data[i], classes[i], result[i], tens);
        }

        // ───── Confidence-threshold decision ─────
        printf("\r\nDecision (threshold = %d.%d%%):\r\n", thr_int, thr_dec);

        if (best_idx < 0) {
            printf("  UNKNOWN (no valid class)\r\n");
        } else if (best_p10 >= CONF_THRESH_X10) {
            int best_int = best_p10 / 10;
            int best_dec = best_p10 % 10;
            printf("  %s (%d.%d%%) accepted as FISH.\r\n",
                   classes[best_idx], best_int, best_dec);
        } else {
            int best_int = best_p10 / 10;
            int best_dec = best_p10 % 10;
            printf("  UNKNOWN (max = %s, %d.%d%% < %d.%d%%)\r\n",
                   classes[best_idx],
                   best_int, best_dec,
                   thr_int, thr_dec);
        }

#ifdef ASCII_ART
        printf("\nASCII preview (downsampled by %d):\n", ASCII_RATIO);
        asciiart((uint8_t *)input_0);
        printf("\nEnd of ASCII frame.\n\n");
#endif

        printf("********** Press PB1 (SW1) to capture an image **********\r\n");
        while (!PB_Get(0)) {
            // wait for next capture trigger
        }
    }

    return 0;
}
